# Create a GitLab Personal Access Token with `read_registry`
# Use `docker login REGISTRY` to login in to it
#
# Follow the instructions here to create the secret:
# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
#
# After that follow the guide here to add the registry secret to the ServiceAccount
# named `gitlab-ci` in the project namespace.
# Like this:
# `kubectl patch serviceaccount gitlab-ci -p '{"imagePullSecrets": [{"name": "gitlab-ci"}]}'`
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-ci
  namespace: presentation-gitlab-k8s
data:
  .dockerconfigjson: UmVhbGx5IHJlYWxseSByZWVlZWVlZWVlZWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGx5eXl5eXl5eXl5eXl5eXl5eXl5eSBsbGxsbGxsbGxsbGxsbG9vb29vb29vb29vb29vb29vb29vb29vb29vb25ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubmdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2cgYXV0aCBrZXlzCg==
type: kubernetes.io/dockerconfigjson
