# For more information on the Prometheus Custom Resource and
# prometheus-operator other CRs, checkout:
# * https://github.com/prometheus-operator/prometheus-operator
# * https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: presentation-gitlab-k8s
  namespace: zerbytes-live-proj-monitoring
  labels:
    app: presentation-gitlab-k8s
    prometheus: zerbytes-apl
spec:
  selector:
    matchLabels:
      app: presentation-gitlab-k8s
  namespaceSelector:
    matchNames:
    - presentation-gitlab-k8s
  endpoints:
  - port: http-metrics
    interval: 15s
